# SPDX-FileCopyrightText: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception

Module: dune-grid
Version: 2.11-git
Author: The Dune Core developers
Maintainer: dune-devel@lists.dune-project.org
Description: module providing main interfaces for setting and traversing grids
URL: https://gitlab.dune-project.org/core/dune-grid
Python-Requires:
Depends: dune-geometry (>= 2.11)
Suggests: dune-uggrid (>=2.11)
Whitespace-Hook: Yes
